plugins {
    id 'com.android.application'
}

android {
    namespace 'com.pichaplus.app'
    compileSdk 34
    defaultConfig {
        applicationId "com.pichaplus.app"
        minSdk 24
        targetSdk 34
        versionCode 10
        versionName "1.10"
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {}
